#!/usr/bin/env bash
#
# pi sync setup wizard (ADR 0007): registers the GitHub OAuth app the pi sync
# device flow needs and stores its client id where the tool reads it.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=2

# Where the pi sync tool reads the client id: the sync state directory, which
# honors PI_SYNC_STATE_DIR, then PI_SYNC_HOME, then the OS home.
STATE_DIR="${PI_SYNC_STATE_DIR:-${PI_SYNC_HOME:-$HOME}/.pi/sync}"
CLIENT_ID_FILE="$STATE_DIR/oauth-client.json"
EXISTING_ID=""
if [[ -f "$CLIENT_ID_FILE" ]]; then
  EXISTING_ID=$(sed -n 's/.*"oauthClientId"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$CLIENT_ID_FILE" | head -n1) || true
fi

banner "pi sync setup (GitHub OAuth app)"
note "The pi sync tool authenticates with the GitHub device flow (ADR 0007)."
note "That flow needs one registered OAuth app per account. No client secret"
note "is ever stored: the device flow does not use one."

# ── Stage 1: register the OAuth app, capture the client id ────────────────
stage "GitHub: register the OAuth app"
say "We create one OAuth app on your account and copy its public client id."
open_url "https://github.com/settings/developers"
step "Click 'New OAuth App' (the green button, upper right)."
step "Name: pi sync. Description: optional."
step "Authorization callback URL: http://127.0.0.1 (the device flow never uses it, but GitHub requires one)."
step "Check 'Use expiring tokens': pi sync renews an 8-hour token with its refresh token (ADR 0007)."
step "Leave 'Delete unapproved apps' unchecked, then click 'Register application'."
step "On the app's settings page, copy the Client ID (20 or more hex characters)."
if [[ -n "$EXISTING_ID" ]]; then
  printf '  %s%s%s %s[Enter keeps %s]%s ' "$BOLD" "Paste the client id:" "$RESET" "$DIM" "$EXISTING_ID" "$RESET"
else
  printf '  %s%s%s ' "$BOLD" "Paste the client id:" "$RESET"
fi
read -r CLIENT_ID || true
[[ -z "$CLIENT_ID" ]] && CLIENT_ID="$EXISTING_ID"
if [[ ! "$CLIENT_ID" =~ ^[0-9a-fA-F]{10,40}$ ]]; then
  warn "that does not look like a GitHub client id (10-40 hex chars)."
  if ! confirm "Store it anyway?"; then
    exit 1
  fi
fi

# Verify the id against GitHub before storing it: a live id gets a throwaway
# device code (harmless; it expires if never used), a typo gets
# invalid_client. Offline, or without curl, it degrades to a warning and a
# confirm. PI_SYNC_GITHUB_BASE_URL points the check at a test stub.
BASE_URL="${PI_SYNC_GITHUB_BASE_URL:-https://github.com}"
if command -v curl >/dev/null 2>&1; then
  response=$(curl -fsS -m 10 -X POST "${BASE_URL}/login/device/code" \
    -H "Accept: application/json" --data "client_id=${CLIENT_ID}&scope=gist" 2>/dev/null) || response=""
  if printf '%s' "$response" | grep -q '"user_code"'; then
    printf '  %s✓ verified against GitHub: the client id is live%s\n' "$GREEN" "$RESET"
  else
    warn "GitHub did not accept that client id (typo, or no network)."
    if ! confirm "Store it anyway?"; then
      exit 1
    fi
  fi
else
  note "curl is not installed; skipping the live check against GitHub."
fi

# ── Stage 2: store the client id where the tool reads it ──────────────────
stage "Store the client id"
say "The wizard writes the id to:"
say "  $CLIENT_ID_FILE"
if [[ -n "$EXISTING_ID" && "$EXISTING_ID" != "$CLIENT_ID" ]]; then
  if ! confirm "Replace the existing client id ($EXISTING_ID)?"; then
    note "keeping the existing client id; nothing written."
    exit 0
  fi
fi
if [[ -n "$EXISTING_ID" && "$EXISTING_ID" == "$CLIENT_ID" ]]; then
  note "already stored: $CLIENT_ID - no change needed."
else
  mkdir -p "$STATE_DIR"
  printf '{\n  "oauthClientId": "%s"\n}\n' "$CLIENT_ID" > "$CLIENT_ID_FILE"
  chmod 600 "$CLIENT_ID_FILE"
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$CLIENT_ID_FILE"
fi

# ──────────────────────────────────────────────────────────────────────────
finish
say "Next step: run 'pi-sync init' (no arguments). It opens the device flow,"
say "shows a short code, and you enter that code in the browser. The gist is"
say "created only after you confirm the preview."
